const data = {
  marketSummaryResponse: {
    result: [
      {
        fullExchangeName: "SNP",
        exchangeTimezoneName: "America/New_York",
        symbol: "^GSPC",
        regularMarketChange: {
          raw: 51.089844,
          fmt: "51.09",
        },
        gmtOffSetMilliseconds: -18000000,
        firstTradeDateMilliseconds: -1325583000000,
        exchangeDataDelayedBy: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302608,
          fmt: "11:56AM EST",
        },
        regularMarketChangePercent: {
          raw: 1.174498,
          fmt: "1.17%",
        },
        exchangeTimezoneShortName: "EST",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 4401.02,
          fmt: "4,401.02",
        },
        marketState: "REGULAR",
        market: "us_market",
        quoteSourceName: "Free Realtime Quote",
        priceHint: 2,
        tradeable: false,
        sourceInterval: 15,
        exchange: "SNP",
        shortName: "S&P 500",
        region: "US",
        regularMarketPreviousClose: {
          raw: 4349.93,
          fmt: "4,349.93",
        },
        triggerable: false,
      },
      {
        fullExchangeName: "DJI",
        exchangeTimezoneName: "America/New_York",
        symbol: "^DJI",
        regularMarketChange: {
          raw: 481.58203,
          fmt: "481.58",
        },
        gmtOffSetMilliseconds: -18000000,
        firstTradeDateMilliseconds: 694362600000,
        exchangeDataDelayedBy: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302608,
          fmt: "11:56AM EST",
        },
        regularMarketChangePercent: {
          raw: 1.4094497,
          fmt: "1.41%",
        },
        exchangeTimezoneShortName: "EST",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 34649.67,
          fmt: "34,649.67",
        },
        marketState: "REGULAR",
        market: "us_market",
        quoteSourceName: "Free Realtime Quote",
        priceHint: 2,
        tradeable: false,
        sourceInterval: 120,
        exchange: "DJI",
        shortName: "Dow 30",
        region: "US",
        regularMarketPreviousClose: {
          raw: 34168.09,
          fmt: "34,168.09",
        },
        triggerable: false,
      },
      {
        fullExchangeName: "Nasdaq GIDS",
        exchangeTimezoneName: "America/New_York",
        symbol: "^IXIC",
        regularMarketChange: {
          raw: 100.37793,
          fmt: "100.38",
        },
        gmtOffSetMilliseconds: -18000000,
        firstTradeDateMilliseconds: 34612200000,
        exchangeDataDelayedBy: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302605,
          fmt: "11:56AM EST",
        },
        regularMarketChangePercent: {
          raw: 0.7412276,
          fmt: "0.74%",
        },
        exchangeTimezoneShortName: "EST",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 13642.497,
          fmt: "13,642.50",
        },
        marketState: "REGULAR",
        market: "us_market",
        quoteSourceName: "Free Realtime Quote",
        priceHint: 2,
        tradeable: false,
        sourceInterval: 15,
        exchange: "NIM",
        shortName: "Nasdaq",
        region: "US",
        regularMarketPreviousClose: {
          raw: 13542.119,
          fmt: "13,542.12",
        },
        triggerable: false,
      },
      {
        fullExchangeName: "Chicago Options",
        exchangeTimezoneName: "America/New_York",
        symbol: "^RUT",
        regularMarketChange: {
          raw: -0.7930908,
          fmt: "-0.79",
        },
        gmtOffSetMilliseconds: -18000000,
        firstTradeDateMilliseconds: 558279000000,
        exchangeDataDelayedBy: 20,
        language: "en-US",
        regularMarketTime: {
          raw: 1643301705,
          fmt: "11:41AM EST",
        },
        regularMarketChangePercent: {
          raw: -0.04012675,
          fmt: "-0.04%",
        },
        exchangeTimezoneShortName: "EST",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 1975.6711,
          fmt: "1,975.67",
        },
        marketState: "REGULAR",
        market: "us_market",
        priceHint: 2,
        tradeable: false,
        sourceInterval: 15,
        exchange: "WCB",
        shortName: "Russell 2000",
        region: "US",
        regularMarketPreviousClose: {
          raw: 1976.4642,
          fmt: "1,976.46",
        },
        triggerable: false,
      },
      {
        fullExchangeName: "NY Mercantile",
        symbol: "CL=F",
        gmtOffSetMilliseconds: -18000000,
        headSymbolAsString: "CL=F",
        language: "en-US",
        regularMarketTime: {
          raw: 1643302010,
          fmt: "11:46AM EST",
        },
        regularMarketChangePercent: {
          raw: -0.14882343,
          fmt: "-0.15%",
        },
        headSymbol: true,
        quoteType: "FUTURE",
        tradeable: false,
        contractSymbol: false,
        regularMarketPreviousClose: {
          raw: 87.35,
          fmt: "87.35",
        },
        exchangeTimezoneName: "America/New_York",
        regularMarketChange: {
          raw: -0.12999725,
          fmt: "-0.13",
        },
        firstTradeDateMilliseconds: 967003200000,
        exchangeDataDelayedBy: 30,
        exchangeTimezoneShortName: "EST",
        marketState: "REGULAR",
        regularMarketPrice: {
          raw: 87.22,
          fmt: "87.22",
        },
        market: "us24_market",
        sourceInterval: 30,
        exchange: "NYM",
        shortName: "Crude Oil",
        region: "US",
        triggerable: false,
      },
      {
        fullExchangeName: "COMEX",
        symbol: "GC=F",
        gmtOffSetMilliseconds: -18000000,
        headSymbolAsString: "GC=F",
        language: "en-US",
        regularMarketTime: {
          raw: 1643302004,
          fmt: "11:46AM EST",
        },
        regularMarketChangePercent: {
          raw: -1.9566009,
          fmt: "-1.96%",
        },
        headSymbol: true,
        quoteType: "FUTURE",
        tradeable: false,
        contractSymbol: false,
        regularMarketPreviousClose: {
          raw: 1829.7,
          fmt: "1,829.70",
        },
        exchangeTimezoneName: "America/New_York",
        regularMarketChange: {
          raw: -35.799927,
          fmt: "-35.80",
        },
        firstTradeDateMilliseconds: 967608000000,
        exchangeDataDelayedBy: 30,
        exchangeTimezoneShortName: "EST",
        marketState: "REGULAR",
        regularMarketPrice: {
          raw: 1793.9,
          fmt: "1,793.90",
        },
        market: "us24_market",
        sourceInterval: 15,
        exchange: "CMX",
        shortName: "Gold",
        region: "US",
        triggerable: false,
      },
      {
        fullExchangeName: "COMEX",
        symbol: "SI=F",
        gmtOffSetMilliseconds: -18000000,
        headSymbolAsString: "SI=F",
        language: "en-US",
        regularMarketTime: {
          raw: 1643302008,
          fmt: "11:46AM EST",
        },
        regularMarketChangePercent: {
          raw: -4.5028715,
          fmt: "-4.50%",
        },
        headSymbol: true,
        quoteType: "FUTURE",
        tradeable: false,
        contractSymbol: false,
        regularMarketPreviousClose: {
          raw: 23.807,
          fmt: "23.81",
        },
        exchangeTimezoneName: "America/New_York",
        regularMarketChange: {
          raw: -1.0719986,
          fmt: "-1.07",
        },
        firstTradeDateMilliseconds: 967608000000,
        exchangeDataDelayedBy: 30,
        exchangeTimezoneShortName: "EST",
        marketState: "REGULAR",
        regularMarketPrice: {
          raw: 22.735,
          fmt: "22.74",
        },
        market: "us24_market",
        sourceInterval: 15,
        exchange: "CMX",
        shortName: "Silver",
        region: "US",
        triggerable: false,
      },
      {
        fullExchangeName: "CCY",
        symbol: "EURUSD=X",
        gmtOffSetMilliseconds: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302588,
          fmt: "4:56PM GMT",
        },
        regularMarketChangePercent: {
          raw: -0.88051724,
          fmt: "-0.88%",
        },
        quoteType: "CURRENCY",
        tradeable: false,
        currency: "USD",
        regularMarketPreviousClose: {
          raw: 1.1244799,
          fmt: "1.1245",
        },
        exchangeTimezoneName: "Europe/London",
        regularMarketChange: {
          raw: -0.009901166,
          fmt: "-0.0099",
        },
        firstTradeDateMilliseconds: 1070236800000,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneShortName: "GMT",
        regularMarketPrice: {
          raw: 1.1145787,
          fmt: "1.1146",
        },
        marketState: "REGULAR",
        market: "ccy_market",
        quoteSourceName: "Delayed Quote",
        priceHint: 4,
        exchange: "CCY",
        sourceInterval: 15,
        region: "US",
        shortName: "EUR/USD",
        triggerable: false,
      },
      {
        fullExchangeName: "ICE Futures",
        exchangeTimezoneName: "America/New_York",
        symbol: "^TNX",
        regularMarketChange: {
          raw: -0.03999996,
          fmt: "-0.0400",
        },
        gmtOffSetMilliseconds: -18000000,
        firstTradeDateMilliseconds: -252356400000,
        exchangeDataDelayedBy: 30,
        language: "en-US",
        regularMarketTime: {
          raw: 1643301703,
          fmt: "11:41AM EST",
        },
        regularMarketChangePercent: {
          raw: -2.1645002,
          fmt: "-2.16%",
        },
        exchangeTimezoneShortName: "EST",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 1.808,
          fmt: "1.8080",
        },
        marketState: "REGULAR",
        market: "us24_market",
        priceHint: 4,
        tradeable: false,
        sourceInterval: 30,
        exchange: "NYB",
        shortName: "10-Yr Bond",
        region: "US",
        regularMarketPreviousClose: {
          raw: 1.8479999,
          fmt: "1.8480",
        },
        triggerable: false,
        longName: "Treasury Yield 10 Years",
      },
      {
        fullExchangeName: "CCY",
        symbol: "GBPUSD=X",
        gmtOffSetMilliseconds: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302588,
          fmt: "4:56PM GMT",
        },
        regularMarketChangePercent: {
          raw: -0.5649124,
          fmt: "-0.56%",
        },
        quoteType: "CURRENCY",
        tradeable: false,
        currency: "USD",
        regularMarketPreviousClose: {
          raw: 1.3462574,
          fmt: "1.3463",
        },
        exchangeTimezoneName: "Europe/London",
        regularMarketChange: {
          raw: -0.007605195,
          fmt: "-0.0076",
        },
        firstTradeDateMilliseconds: 1070236800000,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneShortName: "GMT",
        regularMarketPrice: {
          raw: 1.3386523,
          fmt: "1.3387",
        },
        marketState: "REGULAR",
        market: "ccy_market",
        quoteSourceName: "Delayed Quote",
        priceHint: 4,
        exchange: "CCY",
        sourceInterval: 15,
        region: "US",
        shortName: "GBP/USD",
        triggerable: false,
      },
      {
        fullExchangeName: "CCY",
        symbol: "JPY=X",
        gmtOffSetMilliseconds: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302608,
          fmt: "4:56PM GMT",
        },
        regularMarketChangePercent: {
          raw: 0.7125359,
          fmt: "0.71%",
        },
        quoteType: "CURRENCY",
        tradeable: false,
        currency: "JPY",
        regularMarketPreviousClose: {
          raw: 114.66,
          fmt: "114.6600",
        },
        exchangeTimezoneName: "Europe/London",
        regularMarketChange: {
          raw: 0.8169937,
          fmt: "0.8170",
        },
        firstTradeDateMilliseconds: 846633600000,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneShortName: "GMT",
        regularMarketPrice: {
          raw: 115.477,
          fmt: "115.4770",
        },
        marketState: "REGULAR",
        market: "ccy_market",
        quoteSourceName: "Delayed Quote",
        priceHint: 4,
        exchange: "CCY",
        sourceInterval: 15,
        region: "US",
        shortName: "USD/JPY",
        triggerable: false,
      },
      {
        fullExchangeName: "CCC",
        exchangeTimezoneName: "UTC",
        symbol: "BTC-USD",
        regularMarketChange: {
          raw: -1614.1055,
          fmt: "-1,614.11",
        },
        gmtOffSetMilliseconds: 0,
        firstTradeDateMilliseconds: 1410912000000,
        exchangeDataDelayedBy: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302500,
          fmt: "4:55PM UTC",
        },
        regularMarketChangePercent: {
          raw: -4.2252827,
          fmt: "-4.23%",
        },
        exchangeTimezoneShortName: "UTC",
        quoteType: "CRYPTOCURRENCY",
        regularMarketPrice: {
          raw: 36587.004,
          fmt: "36,587.00",
        },
        marketState: "REGULAR",
        market: "ccc_market",
        quoteSourceName: "CoinMarketCap",
        tradeable: false,
        sourceInterval: 15,
        exchange: "CCC",
        region: "US",
        regularMarketPreviousClose: {
          raw: 36781.855,
          fmt: "36,781.86",
        },
        triggerable: false,
      },
      {
        fullExchangeName: "Nasdaq GIDS",
        exchangeTimezoneName: "America/New_York",
        symbol: "^CMC200",
        regularMarketChange: {
          raw: 18.186462,
          fmt: "18.19",
        },
        gmtOffSetMilliseconds: -18000000,
        firstTradeDateMilliseconds: 1546266600000,
        exchangeDataDelayedBy: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643302548,
          fmt: "11:55AM EST",
        },
        regularMarketChangePercent: {
          raw: 2.2191985,
          fmt: "2.22%",
        },
        exchangeTimezoneShortName: "EST",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 837.6924,
          fmt: "837.69",
        },
        marketState: "REGULAR",
        market: "us_market",
        quoteSourceName: "Free Realtime Quote",
        priceHint: 2,
        tradeable: false,
        sourceInterval: 15,
        exchange: "NIM",
        shortName: "CMC Crypto 200",
        region: "US",
        regularMarketPreviousClose: {
          raw: 819.5059,
          fmt: "819.51",
        },
        triggerable: false,
      },
      {
        fullExchangeName: "FTSE Index",
        exchangeTimezoneName: "Europe/London",
        symbol: "^FTSE",
        regularMarketChange: {
          raw: 84.53027,
          fmt: "84.53",
        },
        gmtOffSetMilliseconds: 0,
        firstTradeDateMilliseconds: 441964800000,
        exchangeDataDelayedBy: 15,
        language: "en-US",
        regularMarketTime: {
          raw: 1643301330,
          fmt: "4:35PM GMT",
        },
        regularMarketChangePercent: {
          raw: 1.1316301,
          fmt: "1.13%",
        },
        exchangeTimezoneShortName: "GMT",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 7554.31,
          fmt: "7,554.31",
        },
        marketState: "POST",
        market: "gb_market",
        priceHint: 2,
        tradeable: false,
        sourceInterval: 15,
        exchange: "FGI",
        shortName: "FTSE 100",
        region: "US",
        regularMarketPreviousClose: {
          raw: 7469.78,
          fmt: "7,469.78",
        },
        triggerable: false,
      },
      {
        fullExchangeName: "Osaka",
        exchangeTimezoneName: "Asia/Tokyo",
        symbol: "^N225",
        regularMarketChange: {
          raw: -841.0293,
          fmt: "-841.03",
        },
        gmtOffSetMilliseconds: 32400000,
        firstTradeDateMilliseconds: -157420800000,
        exchangeDataDelayedBy: 0,
        language: "en-US",
        regularMarketTime: {
          raw: 1643264102,
          fmt: "3:15PM JST",
        },
        regularMarketChangePercent: {
          raw: -3.1136167,
          fmt: "-3.11%",
        },
        exchangeTimezoneShortName: "JST",
        quoteType: "INDEX",
        regularMarketPrice: {
          raw: 26170.3,
          fmt: "26,170.30",
        },
        marketState: "PREPRE",
        market: "jp_market",
        priceHint: 2,
        tradeable: false,
        sourceInterval: 20,
        exchange: "OSA",
        shortName: "Nikkei 225",
        region: "US",
        regularMarketPreviousClose: {
          raw: 27011.33,
          fmt: "27,011.33",
        },
        triggerable: false,
      },
    ],
    error: null,
  },
};
export default data;
